export type ChampionRole = 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
export type DamageType = 'AD' | 'AP' | 'MIXED' | 'TRUE' | 'TANK';
export type ChampionClass = 'TANK' | 'FIGHTER' | 'ASSASSIN' | 'MAGE' | 'MARKSMAN' | 'ENCHANTER' | 'CATCHER' | 'SUPPORT'

export interface Champion {
    id: string;        
    name: string;      
    roles: ChampionRole[]; 
    class: ChampionClass;
    damageType: DamageType;
    
    difficulty: number; 
    earlyGame: number;  
    midGame: number;    
    lateGame: number;   
}

export const CHAMPIONS_DB: Champion[] = [
    // --- TOP LANERS ---
    { id: "Aatrox", name: "Aatrox", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 6, earlyGame: 7, midGame: 9, lateGame: 6 },
    { id: "Ambessa", name: "Ambessa", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 8, earlyGame: 7, midGame: 9, lateGame: 6 },
    { id: "Camille", name: "Camille", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 8, earlyGame: 5, midGame: 8, lateGame: 9 },
    { id: "Chogath", name: "Cho'Gath", roles: ["TOP", "MID"], class: "TANK", damageType: "AP", difficulty: 5, earlyGame: 4, midGame: 7, lateGame: 9 },
    { id: "Darius", name: "Darius", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 3, earlyGame: 9, midGame: 7, lateGame: 4 },
    { id: "DrMundo", name: "Dr. Mundo", roles: ["TOP"], class: "TANK", damageType: "AD", difficulty: 2, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Fiora", name: "Fiora", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 9, earlyGame: 6, midGame: 9, lateGame: 10 },
    { id: "Gangplank", name: "Gangplank", roles: ["TOP", "MID"], class: "FIGHTER", damageType: "AD", difficulty: 10, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Garen", name: "Garen", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 1, earlyGame: 6, midGame: 8, lateGame: 6 },
    { id: "Gnar", name: "Gnar", roles: ["TOP"], class: "TANK", damageType: "AD", difficulty: 7, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Gwen", name: "Gwen", roles: ["TOP", "JUNGLE"], class: "FIGHTER", damageType: "AP", difficulty: 6, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Illaoi", name: "Illaoi", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 5, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Irelia", name: "Irelia", roles: ["TOP", "MID"], class: "FIGHTER", damageType: "AD", difficulty: 8, earlyGame: 6, midGame: 9, lateGame: 9 },
    { id: "Jax", name: "Jax", roles: ["TOP", "JUNGLE"], class: "FIGHTER", damageType: "MIXED", difficulty: 5, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Jayce", name: "Jayce", roles: ["TOP", "MID"], class: "FIGHTER", damageType: "AD", difficulty: 9, earlyGame: 8, midGame: 9, lateGame: 5 },
    { id: "Kayle", name: "Kayle", roles: ["TOP", "MID"], class: "FIGHTER", damageType: "MIXED", difficulty: 7, earlyGame: 2, midGame: 6, lateGame: 10 },
    { id: "Kennen", name: "Kennen", roles: ["TOP", "MID"], class: "MAGE", damageType: "AP", difficulty: 4, earlyGame: 7, midGame: 9, lateGame: 7 },
    { id: "Kled", name: "Kled", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 6, earlyGame: 8, midGame: 7, lateGame: 6 },
    { id: "KSante", name: "K'Sante", roles: ["TOP"], class: "TANK", damageType: "AD", difficulty: 10, earlyGame: 5, midGame: 8, lateGame: 8 },
    { id: "Malphite", name: "Malphite", roles: ["TOP", "MID"], class: "TANK", damageType: "AP", difficulty: 1, earlyGame: 4, midGame: 8, lateGame: 8 },
    { id: "Mordekaiser", name: "Mordekaiser", roles: ["TOP"], class: "FIGHTER", damageType: "AP", difficulty: 4, earlyGame: 6, midGame: 9, lateGame: 8 },
    { id: "Nasus", name: "Nasus", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 3, earlyGame: 4, midGame: 6, lateGame: 10 },
    { id: "Olaf", name: "Olaf", roles: ["TOP", "JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 4, earlyGame: 9, midGame: 7, lateGame: 5 },
    { id: "Ornn", name: "Ornn", roles: ["TOP"], class: "TANK", damageType: "MIXED", difficulty: 6, earlyGame: 5, midGame: 7, lateGame: 10 },
    { id: "Pantheon", name: "Pantheon", roles: ["TOP", "MID", "SUPPORT"], class: "FIGHTER", damageType: "AD", difficulty: 5, earlyGame: 9, midGame: 7, lateGame: 5 },
    { id: "Quinn", name: "Quinn", roles: ["TOP"], class: "MARKSMAN", damageType: "AD", difficulty: 5, earlyGame: 8, midGame: 8, lateGame: 6 },
    { id: "Renekton", name: "Renekton", roles: ["TOP", "MID"], class: "FIGHTER", damageType: "AD", difficulty: 4, earlyGame: 9, midGame: 8, lateGame: 3 },
    { id: "Riven", name: "Riven", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 10, earlyGame: 7, midGame: 8, lateGame: 7 },
    { id: "Rumble", name: "Rumble", roles: ["TOP", "MID", "JUNGLE"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 7, midGame: 10, lateGame: 6 },
    { id: "Shen", name: "Shen", roles: ["TOP", "SUPPORT"], class: "TANK", damageType: "MIXED", difficulty: 5, earlyGame: 7, midGame: 8, lateGame: 7 },
    { id: "Singed", name: "Singed", roles: ["TOP"], class: "TANK", damageType: "AP", difficulty: 8, earlyGame: 4, midGame: 7, lateGame: 9 },
    { id: "Sion", name: "Sion", roles: ["TOP", "MID"], class: "TANK", damageType: "AD", difficulty: 4, earlyGame: 5, midGame: 7, lateGame: 9 },
    { id: "Teemo", name: "Teemo", roles: ["TOP"], class: "MAGE", damageType: "AP", difficulty: 4, earlyGame: 8, midGame: 7, lateGame: 8 },
    { id: "Tryndamere", name: "Tryndamere", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 4, earlyGame: 7, midGame: 8, lateGame: 8 },
    { id: "Urgot", name: "Urgot", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 6, earlyGame: 5, midGame: 8, lateGame: 9 },
    { id: "Vayne", name: "Vayne", roles: ["TOP", "ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 8, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Volibear", name: "Volibear", roles: ["TOP", "JUNGLE"], class: "FIGHTER", damageType: "MIXED", difficulty: 3, earlyGame: 8, midGame: 8, lateGame: 6 },
    { id: "Yorick", name: "Yorick", roles: ["TOP"], class: "FIGHTER", damageType: "AD", difficulty: 4, earlyGame: 4, midGame: 9, lateGame: 8 },

    // --- JUNGLERS ---
    { id: "Amumu", name: "Amumu", roles: ["JUNGLE", "SUPPORT"], class: "TANK", damageType: "AP", difficulty: 3, earlyGame: 5, midGame: 8, lateGame: 8 },
    { id: "Belveth", name: "Bel'Veth", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 6, earlyGame: 6, midGame: 8, lateGame: 10 },
    { id: "Briar", name: "Briar", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 5, earlyGame: 6, midGame: 9, lateGame: 7 },
    { id: "Diana", name: "Diana", roles: ["JUNGLE", "MID"], class: "FIGHTER", damageType: "AP", difficulty: 6, earlyGame: 6, midGame: 8, lateGame: 8 },
    { id: "Ekko", name: "Ekko", roles: ["JUNGLE", "MID"], class: "ASSASSIN", damageType: "AP", difficulty: 8, earlyGame: 5, midGame: 9, lateGame: 7 },
    { id: "Elise", name: "Elise", roles: ["JUNGLE"], class: "MAGE", damageType: "AP", difficulty: 9, earlyGame: 10, midGame: 6, lateGame: 2 },
    { id: "Evelynn", name: "Evelynn", roles: ["JUNGLE"], class: "ASSASSIN", damageType: "AP", difficulty: 7, earlyGame: 4, midGame: 10, lateGame: 8 },
    { id: "Fiddlesticks", name: "Fiddlesticks", roles: ["JUNGLE"], class: "MAGE", damageType: "AP", difficulty: 6, earlyGame: 5, midGame: 9, lateGame: 9 },
    { id: "Graves", name: "Graves", roles: ["JUNGLE"], class: "MARKSMAN", damageType: "AD", difficulty: 7, earlyGame: 8, midGame: 8, lateGame: 7 },
    { id: "Hecarim", name: "Hecarim", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 5, earlyGame: 6, midGame: 9, lateGame: 7 },
    { id: "Ivern", name: "Ivern", roles: ["JUNGLE"], class: "SUPPORT", damageType: "AP", difficulty: 7, earlyGame: 7, midGame: 8, lateGame: 8 },
    { id: "JarvanIV", name: "Jarvan IV", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 4, earlyGame: 9, midGame: 7, lateGame: 5 },
    { id: "Karthus", name: "Karthus", roles: ["JUNGLE", "MID"], class: "MAGE", damageType: "AP", difficulty: 5, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Kayn", name: "Kayn", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 5, earlyGame: 4, midGame: 10, lateGame: 8 },
    { id: "Khazix", name: "Kha'Zix", roles: ["JUNGLE"], class: "ASSASSIN", damageType: "AD", difficulty: 6, earlyGame: 6, midGame: 9, lateGame: 7 },
    { id: "Kindred", name: "Kindred", roles: ["JUNGLE"], class: "MARKSMAN", damageType: "AD", difficulty: 8, earlyGame: 6, midGame: 7, lateGame: 10 },
    { id: "LeeSin", name: "Lee Sin", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 9, earlyGame: 10, midGame: 7, lateGame: 3 },
    { id: "Lillia", name: "Lillia", roles: ["JUNGLE", "TOP"], class: "MAGE", damageType: "AP", difficulty: 8, earlyGame: 5, midGame: 8, lateGame: 9 },
    { id: "MasterYi", name: "Master Yi", roles: ["JUNGLE"], class: "ASSASSIN", damageType: "AD", difficulty: 2, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Nidalee", name: "Nidalee", roles: ["JUNGLE"], class: "MAGE", damageType: "AP", difficulty: 10, earlyGame: 9, midGame: 7, lateGame: 4 },
    { id: "Nocturne", name: "Nocturne", roles: ["JUNGLE", "MID"], class: "ASSASSIN", damageType: "AD", difficulty: 4, earlyGame: 6, midGame: 10, lateGame: 5 },
    { id: "Nunu", name: "Nunu & Willump", roles: ["JUNGLE"], class: "TANK", damageType: "AP", difficulty: 4, earlyGame: 8, midGame: 7, lateGame: 4 },
    { id: "Rammus", name: "Rammus", roles: ["JUNGLE"], class: "TANK", damageType: "MIXED", difficulty: 3, earlyGame: 7, midGame: 8, lateGame: 8 },
    { id: "RekSai", name: "Rek'Sai", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 7, earlyGame: 9, midGame: 7, lateGame: 4 },
    { id: "Rengar", name: "Rengar", roles: ["JUNGLE", "TOP"], class: "ASSASSIN", damageType: "AD", difficulty: 8, earlyGame: 6, midGame: 8, lateGame: 9 },
    { id: "Sejuani", name: "Sejuani", roles: ["JUNGLE", "TOP"], class: "TANK", damageType: "AP", difficulty: 4, earlyGame: 6, midGame: 8, lateGame: 8 },
    { id: "Shaco", name: "Shaco", roles: ["JUNGLE"], class: "ASSASSIN", damageType: "AD", difficulty: 9, earlyGame: 7, midGame: 9, lateGame: 5 },
    { id: "Shyvana", name: "Shyvana", roles: ["JUNGLE", "TOP"], class: "FIGHTER", damageType: "MIXED", difficulty: 4, earlyGame: 4, midGame: 9, lateGame: 8 },
    { id: "Skarner", name: "Skarner", roles: ["JUNGLE", "TOP"], class: "TANK", damageType: "AD", difficulty: 5, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Taliyah", name: "Taliyah", roles: ["JUNGLE", "MID"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 5, midGame: 9, lateGame: 8 },
    { id: "Trundle", name: "Trundle", roles: ["JUNGLE", "TOP"], class: "FIGHTER", damageType: "AD", difficulty: 3, earlyGame: 6, midGame: 7, lateGame: 8 },
    { id: "Udyr", name: "Udyr", roles: ["JUNGLE", "TOP"], class: "FIGHTER", damageType: "MIXED", difficulty: 4, earlyGame: 7, midGame: 8, lateGame: 6 },
    { id: "Vi", name: "Vi", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 3, earlyGame: 7, midGame: 9, lateGame: 6 },
    { id: "Viego", name: "Viego", roles: ["JUNGLE", "MID"], class: "FIGHTER", damageType: "AD", difficulty: 6, earlyGame: 6, midGame: 8, lateGame: 8 },
    { id: "Warwick", name: "Warwick", roles: ["JUNGLE", "TOP"], class: "FIGHTER", damageType: "AD", difficulty: 2, earlyGame: 8, midGame: 7, lateGame: 7 },
    { id: "MonkeyKing", name: "Wukong", roles: ["JUNGLE", "TOP"], class: "FIGHTER", damageType: "AD", difficulty: 3, earlyGame: 6, midGame: 9, lateGame: 7 },
    { id: "XinZhao", name: "Xin Zhao", roles: ["JUNGLE"], class: "FIGHTER", damageType: "AD", difficulty: 3, earlyGame: 9, midGame: 7, lateGame: 5 },
    { id: "Zac", name: "Zac", roles: ["JUNGLE", "TOP"], class: "TANK", damageType: "AP", difficulty: 5, earlyGame: 5, midGame: 9, lateGame: 9 },

    // --- MID LANERS ---
    { id: "Ahri", name: "Ahri", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 5, earlyGame: 6, midGame: 9, lateGame: 6 },
    { id: "Akali", name: "Akali", roles: ["MID", "TOP"], class: "ASSASSIN", damageType: "AP", difficulty: 9, earlyGame: 5, midGame: 10, lateGame: 6 },
    { id: "Akshan", name: "Akshan", roles: ["MID", "TOP"], class: "MARKSMAN", damageType: "AD", difficulty: 8, earlyGame: 9, midGame: 7, lateGame: 5 },
    { id: "Anivia", name: "Anivia", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Annie", name: "Annie", roles: ["MID", "SUPPORT"], class: "MAGE", damageType: "AP", difficulty: 2, earlyGame: 6, midGame: 9, lateGame: 7 },
    { id: "AurelionSol", name: "Aurelion Sol", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 8, earlyGame: 4, midGame: 9, lateGame: 10 },
    { id: "Azir", name: "Azir", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 10, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Cassiopeia", name: "Cassiopeia", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 8, earlyGame: 6, midGame: 9, lateGame: 8 },
    { id: "Corki", name: "Corki", roles: ["MID", "ADC"], class: "MARKSMAN", damageType: "AP", difficulty: 6, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Fizz", name: "Fizz", roles: ["MID"], class: "ASSASSIN", damageType: "AP", difficulty: 6, earlyGame: 5, midGame: 10, lateGame: 6 },
    { id: "Galio", name: "Galio", roles: ["MID", "SUPPORT"], class: "TANK", damageType: "AP", difficulty: 4, earlyGame: 6, midGame: 9, lateGame: 7 },
    { id: "Heimerdinger", name: "Heimerdinger", roles: ["MID", "TOP", "SUPPORT"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 7, midGame: 9, lateGame: 6 },
    { id: "Hwei", name: "Hwei", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 9, earlyGame: 5, midGame: 9, lateGame: 8 },
    { id: "Kassadin", name: "Kassadin", roles: ["MID"], class: "ASSASSIN", damageType: "AP", difficulty: 8, earlyGame: 3, midGame: 7, lateGame: 10 },
    { id: "Katarina", name: "Katarina", roles: ["MID"], class: "ASSASSIN", damageType: "AP", difficulty: 8, earlyGame: 6, midGame: 9, lateGame: 8 },
    { id: "Leblanc", name: "LeBlanc", roles: ["MID"], class: "ASSASSIN", damageType: "AP", difficulty: 9, earlyGame: 8, midGame: 9, lateGame: 4 },
    { id: "Lissandra", name: "Lissandra", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 5, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Lux", name: "Lux", roles: ["MID", "SUPPORT"], class: "MAGE", damageType: "AP", difficulty: 3, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Malzahar", name: "Malzahar", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 4, earlyGame: 4, midGame: 9, lateGame: 8 },
    { id: "Mel", name: "Mel", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 8, earlyGame: 5, midGame: 9, lateGame: 7 },
    { id: "Naafiri", name: "Naafiri", roles: ["MID"], class: "ASSASSIN", damageType: "AD", difficulty: 4, earlyGame: 6, midGame: 10, lateGame: 6 },
    { id: "Neeko", name: "Neeko", roles: ["MID", "SUPPORT"], class: "MAGE", damageType: "AP", difficulty: 6, earlyGame: 7, midGame: 8, lateGame: 8 },
    { id: "Orianna", name: "Orianna", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 5, midGame: 9, lateGame: 9 },
    { id: "Qiyana", name: "Qiyana", roles: ["MID"], class: "ASSASSIN", damageType: "AD", difficulty: 9, earlyGame: 6, midGame: 10, lateGame: 7 },
    { id: "Ryze", name: "Ryze", roles: ["MID", "TOP"], class: "MAGE", damageType: "AP", difficulty: 9, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Sylas", name: "Sylas", roles: ["MID", "TOP", "JUNGLE"], class: "FIGHTER", damageType: "AP", difficulty: 7, earlyGame: 6, midGame: 9, lateGame: 8 },
    { id: "Syndra", name: "Syndra", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 5, midGame: 9, lateGame: 9 },
    { id: "Talon", name: "Talon", roles: ["MID", "JUNGLE"], class: "ASSASSIN", damageType: "AD", difficulty: 6, earlyGame: 8, midGame: 9, lateGame: 4 },
    { id: "TwistedFate", name: "TwistedFate", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 6, earlyGame: 4, midGame: 10, lateGame: 7 },
    { id: "Veigar", name: "Veigar", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 4, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Velkoz", name: "Vel'Koz", roles: ["MID", "SUPPORT"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Viktor", name: "Viktor", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 7, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Vladimir", name: "Vladimir", roles: ["MID", "TOP"], class: "MAGE", damageType: "AP", difficulty: 6, earlyGame: 3, midGame: 8, lateGame: 10 },
    { id: "Yasuo", name: "Yasuo", roles: ["MID", "TOP"], class: "FIGHTER", damageType: "AD", difficulty: 10, earlyGame: 5, midGame: 8, lateGame: 9 },
    { id: "Yone", name: "Yone", roles: ["MID", "TOP"], class: "ASSASSIN", damageType: "AD", difficulty: 7, earlyGame: 5, midGame: 7, lateGame: 10 },
    { id: "Zed", name: "Zed", roles: ["MID"], class: "ASSASSIN", damageType: "AD", difficulty: 8, earlyGame: 7, midGame: 9, lateGame: 5 },
    { id: "Ziggs", name: "Ziggs", roles: ["MID", "ADC"], class: "MAGE", damageType: "AP", difficulty: 5, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Zoe", name: "Zoe", roles: ["MID"], class: "MAGE", damageType: "AP", difficulty: 8, earlyGame: 7, midGame: 10, lateGame: 5 },

    // --- ADC / MARKSMAN ---
    { id: "Aphelios", name: "Aphelios", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 10, earlyGame: 3, midGame: 7, lateGame: 10 },
    { id: "Ashe", name: "Ashe", roles: ["ADC", "SUPPORT"], class: "MARKSMAN", damageType: "AD", difficulty: 3, earlyGame: 7, midGame: 6, lateGame: 8 },
    { id: "Caitlyn", name: "Caitlyn", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 5, earlyGame: 9, midGame: 5, lateGame: 9 },
    { id: "Draven", name: "Draven", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 9, earlyGame: 10, midGame: 8, lateGame: 4 },
    { id: "Ezreal", name: "Ezreal", roles: ["ADC", "MID"], class: "MARKSMAN", damageType: "MIXED", difficulty: 7, earlyGame: 5, midGame: 10, lateGame: 6 },
    { id: "Jhin", name: "Jhin", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 5, earlyGame: 6, midGame: 9, lateGame: 7 },
    { id: "Jinx", name: "Jinx", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 4, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Kaisa", name: "Kai'Sa", roles: ["ADC"], class: "MARKSMAN", damageType: "MIXED", difficulty: 7, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Kalista", name: "Kalista", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 10, earlyGame: 9, midGame: 7, lateGame: 4 },
    { id: "KogMaw", name: "Kog'Maw", roles: ["ADC"], class: "MARKSMAN", damageType: "MIXED", difficulty: 6, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Lucian", name: "Lucian", roles: ["ADC", "MID"], class: "MARKSMAN", damageType: "AD", difficulty: 7, earlyGame: 8, midGame: 9, lateGame: 4 },
    { id: "MissFortune", name: "Miss Fortune", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 3, earlyGame: 8, midGame: 8, lateGame: 6 },
    { id: "Nilah", name: "Nilah", roles: ["ADC"], class: "FIGHTER", damageType: "AD", difficulty: 8, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Samira", name: "Samira", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 7, earlyGame: 5, midGame: 9, lateGame: 7 },
    { id: "Senna", name: "Senna", roles: ["SUPPORT", "ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 6, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Sivir", name: "Sivir", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 3, earlyGame: 4, midGame: 8, lateGame: 10 },
    { id: "Smolder", name: "Smolder", roles: ["ADC", "MID"], class: "MARKSMAN", damageType: "AD", difficulty: 5, earlyGame: 3, midGame: 7, lateGame: 10 },
    { id: "Tristana", name: "Tristana", roles: ["ADC", "MID"], class: "MARKSMAN", damageType: "AD", difficulty: 3, earlyGame: 7, midGame: 6, lateGame: 10 },
    { id: "Twitch", name: "Twitch", roles: ["ADC", "JUNGLE"], class: "MARKSMAN", damageType: "AD", difficulty: 6, earlyGame: 5, midGame: 8, lateGame: 10 },
    { id: "Varus", name: "Varus", roles: ["ADC", "MID"], class: "MARKSMAN", damageType: "MIXED", difficulty: 6, earlyGame: 7, midGame: 8, lateGame: 7 },
    { id: "Xayah", name: "Xayah", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 7, earlyGame: 5, midGame: 8, lateGame: 9 },
    { id: "Zeri", name: "Zeri", roles: ["ADC"], class: "MARKSMAN", damageType: "AD", difficulty: 8, earlyGame: 4, midGame: 7, lateGame: 10 },

    // --- SUPPORTS ---
    { id: "Alistar", name: "Alistar", roles: ["SUPPORT"], class: "TANK", damageType: "AP", difficulty: 4, earlyGame: 6, midGame: 8, lateGame: 7 },
    { id: "Bard", name: "Bard", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 9, earlyGame: 6, midGame: 9, lateGame: 8 },
    { id: "Blitzcrank", name: "Blitzcrank", roles: ["SUPPORT"], class: "TANK", damageType: "AP", difficulty: 4, earlyGame: 9, midGame: 6, lateGame: 4 },
    { id: "Braum", name: "Braum", roles: ["SUPPORT"], class: "TANK", damageType: "AP", difficulty: 5, earlyGame: 5, midGame: 8, lateGame: 8 },
    { id: "Janna", name: "Janna", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 3, earlyGame: 7, midGame: 7, lateGame: 9 },
    { id: "Karma", name: "Karma", roles: ["SUPPORT", "MID"], class: "MAGE", damageType: "AP", difficulty: 4, earlyGame: 10, midGame: 7, lateGame: 5 },
    { id: "Leona", name: "Leona", roles: ["SUPPORT"], class: "TANK", damageType: "AP", difficulty: 2, earlyGame: 8, midGame: 8, lateGame: 6 },
    { id: "Lulu", name: "Lulu", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 5, earlyGame: 7, midGame: 8, lateGame: 9 },
    { id: "Milio", name: "Milio", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 4, earlyGame: 5, midGame: 7, lateGame: 10 },
    { id: "Morgana", name: "Morgana", roles: ["SUPPORT", "MID"], class: "MAGE", damageType: "AP", difficulty: 3, earlyGame: 7, midGame: 8, lateGame: 7 },
    { id: "Nami", name: "Nami", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 6, earlyGame: 8, midGame: 7, lateGame: 6 },
    { id: "Nautilus", name: "Nautilus", roles: ["SUPPORT"], class: "TANK", damageType: "AP", difficulty: 3, earlyGame: 9, midGame: 8, lateGame: 6 },
    { id: "Pyke", name: "Pyke", roles: ["SUPPORT", "MID"], class: "ASSASSIN", damageType: "AD", difficulty: 8, earlyGame: 10, midGame: 7, lateGame: 3 },
    { id: "Rakan", name: "Rakan", roles: ["SUPPORT"], class: "TANK", damageType: "AP", difficulty: 7, earlyGame: 5, midGame: 9, lateGame: 8 },
    { id: "Rell", name: "Rell", roles: ["SUPPORT", "JUNGLE"], class: "TANK", damageType: "AP", difficulty: 6, earlyGame: 7, midGame: 9, lateGame: 7 },
    { id: "Renata", name: "Renata Glasc", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 7, earlyGame: 5, midGame: 8, lateGame: 10 },
    { id: "Seraphine", name: "Seraphine", roles: ["SUPPORT", "MID", "ADC"], class: "MAGE", damageType: "AP", difficulty: 4, earlyGame: 5, midGame: 8, lateGame: 10 },
    { id: "Sona", name: "Sona", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 2, earlyGame: 4, midGame: 7, lateGame: 10 },
    { id: "Soraka", name: "Soraka", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 3, earlyGame: 7, midGame: 7, lateGame: 9 },
    { id: "Taric", name: "Taric", roles: ["SUPPORT"], class: "TANK", damageType: "MIXED", difficulty: 6, earlyGame: 5, midGame: 8, lateGame: 10 },
    { id: "Thresh", name: "Thresh", roles: ["SUPPORT"], class: "TANK", damageType: "AP", difficulty: 9, earlyGame: 7, midGame: 9, lateGame: 7 },
    { id: "Yuumi", name: "Yuumi", roles: ["SUPPORT"], class: "SUPPORT", damageType: "AP", difficulty: 5, earlyGame: 6, midGame: 8, lateGame: 8 },
    { id: "Zyra", name: "Zyra", roles: ["SUPPORT", "JUNGLE"], class: "MAGE", damageType: "AP", difficulty: 4, earlyGame: 8, midGame: 8, lateGame: 7 }
];
